version: '3.9'

services:
  keycloak:
    container_name: local_keycloak
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
