version: '3.9'

services:
  keycloak:
    container_name: local_keycloak
    image: jboss/keycloak:latest
    ports:
      - "28080:8080"
    networks:
      - local-keycloak

networks:
  local-keycloak:
